site_name: My Docs
nav:
  - Home: index.md
  - tesuto: test.md

theme: readthedocs

markdown_extensions:
  - mdx_math:
      enable_dollar_delimiter: true

extra_javascript:
  - http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML

extra_css:
  - "//fonts.googleapis.com/earlyaccess/notosansjp.css"
  - "//fonts.googleapis.com/css?family=Open+Sans:600,800"
  - "css/custom.css"

